name: request-form-mwi
region: sfo

services:
  - name: the-request-form
    github:
      repo: ColtonBaum/THE-REQuest-form
      branch: main
    environment_slug: python
    instance_count: 2
    instance_size_slug: apps-s-1vcpu-1gb
    build_command: pip install -r requirements.txt
    run_command: python -m alembic -c alembic.ini upgrade head && python app.py
    http_port: 8080

databases:
  - name: db-postgresql-sfo2-54475
    engine: PG
    version: "17"
    cluster_name: db-postgresql-sfo2-54475
    db_name: defaultdb
    db_user: doadmin
    production: true

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: postgresql+psycopg2://doadmin:…@db-postgresql-sfo2-54475-do-user-20036710-0.e.db.ondigitalocean.com:25060/defaultdb?sslmode=require

ingress:
  rules:
    - match:
        path:
          prefix: /
        authority:
          exact: ""
      component:
        name: the-request-form

features:
  - buildpack-stack=ubuntu-22
