"""chore(models): re-add start_date to Job

Revision ID: afd7ae0b78a5
Revises: 48a70c80c80b
Create Date: 2025-06-24 08:59:58.114635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd7ae0b78a5'
down_revision = '48a70c80c80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
